### ISSUE TITLE
Syncing stops after a few minutes

### ISSUE THREAD

**Issue by aghassemi** [vanadium/syncslides#14]
After a few minutes (have not tried to measure it yet, but somewhere between 2 and 10 mins) devices no longer sync with each other. 

Could it be related to how Syncbase mounts the other device under a unique name and maybe it is not refreshing the mount-point causing it to expire after default TTL?

@hpucha @asadovsky  @rdvg

**Comment by asadovsky** [comment]
I wonder if this might be related to the problem Kishore also observed, and which @suharshs was debugging?
Are you using v23 proxy? From chatting with Suharsh today, it sounds like there may be bugs in the proxy, and these bugs may only get triggered after some time passes.

**Comment by aghassemi** [comment]
Not using proxy. Will provide more details after updating all dependencies and retrying.

**Comment by aghassemi** [comment]
No longer an issue with 0.0.17
