### ISSUE TITLE
Data is not persisted anymore

### ISSUE THREAD

**Issue by aghassemi** [vanadium/syncslides#15]
Decks added from previous runs do not come back from the `scan` anymore. This used to work fine.

Tables seem to exist, but scan does not seem to see them:

SyncSlides: 2015-11-24 10:07:25.900: Table decks already exists.
SyncSlides: 2015-11-24 10:07:25.928: Table presentations already exists.
Error(id: v.io/v23/query/syncql.TableCantAccess, actionCode: 0, msg: syncbase_server.mojo: [17]Table presentations does not exist (or cannot be accessed): syncbase_server.mojo: Internal error: syncbase_server.mojo: Canceled: aborted snapshot.)

Might be Mojo or Syncbase related.

@asadovsky

**Comment by asadovsky** [comment]
Are you still seeing this? Can you give more information about the specifics of your setup? Could it be a permissions issue? Your error message is from exec; do you know if scan does the same? What happens if you try to scan/exec using vrpc or namespace browser?

**Comment by aghassemi** [comment]
This one is strange. It was fine with the same version of Syncbase (0.15) before. I have a feeling it is related to Mojo changes. Maybe Mojo is corrupting/deleting files on exit. I will reproduce after updating dependencies to latest.

**Comment by aghassemi** [comment]
Fix to come. Issue was that I was aborting a readonly batch before finishing reading all the data first, causing my query stream to be broken at an arbitrary point when `abort` actually happened.

https://github.com/vanadium/issues/issues/959 for usability improvement.
