### ISSUE TITLE
Joining a presentation goes to slidelist page instead of slideshow 

### ISSUE THREAD

**Issue by aghassemi** [vanadium/syncslides#22]
Regression likely due to Flutter's change of behaviour with Navigators. We do a push of listslide page before pushing the slideshow so back button goes back to list, this is probably the cause of this issue.

if we can't find a easy solution for this, we don't need to have the back button go to slidelist page so we can just push the slideshow.

**Comment by mishadynin** [comment]
Accepted, can reproduce, looking into it.

**Comment by mishadynin** [comment]
Fixed in https://github.com/vanadium/syncslides/commit/839cee7af5cb94b28b28ca957787b6a9a81ad704.
