### ISSUE TITLE
Figure out how we can package up and install the app

### ISSUE THREAD

**Issue by aghassemi** [vanadium/syncslides#3]
We need to be able to run the app without needing to be connected to USB and doing a flutter_tools run_mojo etc... We need to find a way.

Other teams have managed to publish their apps on a CDN and has a webpage with mojo links in them that open and download the apps. We need something like that.

@mishadynin

**Comment by aghassemi** [comment]
This may help a lot: https://github.com/domokit/mojo/issues/550 

config file can be in a "known" location and then we can just create a shortcut

**Comment by mishadynin** [comment]
Yes, we should be able to create a shortcut using the command described in the linked issue:

```
./mojo/devtools/common/mojo_run --android 'mojo:shortcut SlidesAppName mojo://www.example.com/foo.mojo http://example.com/icon.jpg'
```

**Comment by aghassemi** [comment]
Yes, @afandria did this for Croupier: https://vanadium-review.googlesource.com/#/c/18010/ we should do something similar and maybe figure out how to share that code.
